### PR TITLE
Feature/constant power

### PR DESCRIPTION
**Pull request by dougszumski**
This isn't finished yet, but seems to work. Power is hard coded at 300W. The PID constants seems to be reasonable, although there are some slight signs of oscillation in the data.

There's a minimum power below which it doesn't engage, and the PID gets reset.

### CODE REVIEW

**Comment by dougszumski** [comment]
Another test, from the logs it looks like the resistance hit the minimum at the end. We probably need some indicator to tell people to change gear!
test

**Comment by jovial** [comment]
Yeah, good job. Merge when ready.

**Comment by jovial** [comment]
I know we set the resistance to zero at the end of the course. Maybe we should leave it unchanged? Or, ramp it down over the period of a minute or so?

**Comment by dougszumski** [comment]
Hmm, yeah, perhaps we could leave it unchanged, and then people could define warm down routines for afterwards.

**Comment by dougszumski** [comment]
Merging for now as it seems to work. Will re-open a new request for the GUI and other updates.

**Pull request merged**
